<template>
  <header class="mt-10 mb-20 px-10">
    <h1 class="home-title text-4xl font-mono font-bold text-center">
      <nuxt-link to="/">Harvest Hill - Organic Fruit Market</nuxt-link>
    </h1>
    <button class="snipcart-checkout block mx-auto mt-4">
      <span class="snipcart-items-count">0</span> 🍓 in the 🛒
    </button>
  </header>
</template>

<script>
export default {
  components: {},
}
</script>